development:
  adapter: postgresql
  encoding: unicode
  database: rez_backbone_development
  pool: 5
  host: localhost
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rez_backbone_test
  pool: 5
  host: localhost
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rez_backbone_production
  pool: 5
  host: localhost
  username:
  password:
